name: 'Run the SAU/CAL CI Bot'
description: ''
inputs:
  bot_token:
    description: 'The Bots token. Usually configured in the repo settings'
    required: true
    default: ''
  phpcs_enabled:
    description: 'Whether to enable PHPCS or not'
    required: false
    default: 'true'
  linting_enabled:
    description: 'Whether to enable Linting or not'
    required: false
    default: 'true'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: ci-bot.sh
      shell: bash
      env:
        REPO_TOKEN: ${{ inputs.bot_token }}
        PHPCS_ENABLED: ${{ inputs.phpcs_enabled }}
        LINTING_ENABLED: ${{ inputs.linting_enabled }}
